package com.company.model;

import com.company.model.Playfield;
import com.company.model.TileType;
import com.company.model.Tile;
public class GEN_PlayfieldCreator {
public static int getNumRows() { return 12;}public static int getNumColumns() { return 15;}public static int getNumPlayers() { return 4;}public static int getNumPiecesPerPlayer(int id) { if (id <= 4) {switch (id) {case 1: return 4;case 2: return 4;case 3: return 8;case 4: return 4;}}else throw new Error("player doesnt exist");return -1;}	public static void createPlayfield(Playfield playfield) {
playfield.setupTiles();
playfield.getTile(0, 0).setType(TileType.HOME).setPlayerID(1);
playfield.getTile(0, 1).setType(TileType.HOME).setPlayerID(1);
playfield.getTile(0, 2).setType(TileType.NONE);
playfield.getTile(0, 3).setType(TileType.NONE);
playfield.getTile(0, 4).setType(TileType.WAY).setNext(playfield.getTile(0, 5));
playfield.getTile(0, 5).setType(TileType.TOGOAL).setNext(playfield.getTile(0, 6)).setGoal(playfield.getTile(1, 5));
playfield.getTile(0, 6).setType(TileType.START).setNext(playfield.getTile(1, 6)).setPlayerID(2);
playfield.getTile(0, 7).setType(TileType.NONE);
playfield.getTile(0, 8).setType(TileType.NONE);
playfield.getTile(0, 9).setType(TileType.NONE);
playfield.getTile(0, 10).setType(TileType.NONE);
playfield.getTile(0, 11).setType(TileType.NONE);
playfield.getTile(0, 12).setType(TileType.NONE);
playfield.getTile(0, 13).setType(TileType.HOME).setPlayerID(2);
playfield.getTile(0, 14).setType(TileType.HOME).setPlayerID(2);
playfield.getTile(1, 0).setType(TileType.HOME).setPlayerID(1);
playfield.getTile(1, 1).setType(TileType.HOME).setPlayerID(1);
playfield.getTile(1, 2).setType(TileType.NONE);
playfield.getTile(1, 3).setType(TileType.NONE);
playfield.getTile(1, 4).setType(TileType.WAY).setNext(playfield.getTile(0, 4));
playfield.getTile(1, 5).setType(TileType.GOAL).setNext(playfield.getTile(2, 5)).setPlayerID(2);
playfield.getTile(1, 6).setType(TileType.WAY).setNext(playfield.getTile(2, 6));
playfield.getTile(1, 7).setType(TileType.NONE);
playfield.getTile(1, 8).setType(TileType.NONE);
playfield.getTile(1, 9).setType(TileType.NONE);
playfield.getTile(1, 10).setType(TileType.NONE);
playfield.getTile(1, 11).setType(TileType.NONE);
playfield.getTile(1, 12).setType(TileType.NONE);
playfield.getTile(1, 13).setType(TileType.HOME).setPlayerID(2);
playfield.getTile(1, 14).setType(TileType.HOME).setPlayerID(2);
playfield.getTile(2, 0).setType(TileType.NONE);
playfield.getTile(2, 1).setType(TileType.NONE);
playfield.getTile(2, 2).setType(TileType.NONE);
playfield.getTile(2, 3).setType(TileType.NONE);
playfield.getTile(2, 4).setType(TileType.WAY).setNext(playfield.getTile(1, 4));
playfield.getTile(2, 5).setType(TileType.GOAL).setNext(playfield.getTile(3, 5)).setPlayerID(2);
playfield.getTile(2, 6).setType(TileType.WAY).setNext(playfield.getTile(3, 6));
playfield.getTile(2, 7).setType(TileType.NONE);
playfield.getTile(2, 8).setType(TileType.NONE);
playfield.getTile(2, 9).setType(TileType.NONE);
playfield.getTile(2, 10).setType(TileType.NONE);
playfield.getTile(2, 11).setType(TileType.NONE);
playfield.getTile(2, 12).setType(TileType.NONE);
playfield.getTile(2, 13).setType(TileType.NONE);
playfield.getTile(2, 14).setType(TileType.NONE);
playfield.getTile(3, 0).setType(TileType.NONE);
playfield.getTile(3, 1).setType(TileType.NONE);
playfield.getTile(3, 2).setType(TileType.NONE);
playfield.getTile(3, 3).setType(TileType.NONE);
playfield.getTile(3, 4).setType(TileType.WAY).setNext(playfield.getTile(2, 4));
playfield.getTile(3, 5).setType(TileType.GOAL).setNext(playfield.getTile(4, 5)).setPlayerID(2);
playfield.getTile(3, 6).setType(TileType.WAY).setNext(playfield.getTile(4, 6));
playfield.getTile(3, 7).setType(TileType.NONE);
playfield.getTile(3, 8).setType(TileType.NONE);
playfield.getTile(3, 9).setType(TileType.NONE);
playfield.getTile(3, 10).setType(TileType.NONE);
playfield.getTile(3, 11).setType(TileType.NONE);
playfield.getTile(3, 12).setType(TileType.NONE);
playfield.getTile(3, 13).setType(TileType.NONE);
playfield.getTile(3, 14).setType(TileType.NONE);
playfield.getTile(4, 0).setType(TileType.START).setNext(playfield.getTile(4, 1)).setPlayerID(1);
playfield.getTile(4, 1).setType(TileType.WAY).setNext(playfield.getTile(4, 2));
playfield.getTile(4, 2).setType(TileType.WAY).setNext(playfield.getTile(4, 3));
playfield.getTile(4, 3).setType(TileType.WAY).setNext(playfield.getTile(4, 4));
playfield.getTile(4, 4).setType(TileType.WAY).setNext(playfield.getTile(4, 5));
playfield.getTile(4, 5).setType(TileType.GOAL).setPlayerID(2);
playfield.getTile(4, 6).setType(TileType.WAY).setNext(playfield.getTile(4, 7));
playfield.getTile(4, 7).setType(TileType.WAY).setNext(playfield.getTile(4, 8));
playfield.getTile(4, 8).setType(TileType.WAY).setNext(playfield.getTile(4, 9));
playfield.getTile(4, 9).setType(TileType.WAY).setNext(playfield.getTile(4, 10));
playfield.getTile(4, 10).setType(TileType.WAY).setNext(playfield.getTile(4, 11));
playfield.getTile(4, 11).setType(TileType.WAY).setNext(playfield.getTile(4, 12));
playfield.getTile(4, 12).setType(TileType.WAY).setNext(playfield.getTile(4, 13));
playfield.getTile(4, 13).setType(TileType.WAY).setNext(playfield.getTile(4, 14));
playfield.getTile(4, 14).setType(TileType.WAY).setNext(playfield.getTile(5, 14));
playfield.getTile(5, 0).setType(TileType.TOGOAL).setNext(playfield.getTile(4, 0)).setGoal(playfield.getTile(5, 1));
playfield.getTile(5, 1).setType(TileType.GOAL).setNext(playfield.getTile(5, 2)).setPlayerID(1);
playfield.getTile(5, 2).setType(TileType.GOAL).setNext(playfield.getTile(5, 3)).setPlayerID(1);
playfield.getTile(5, 3).setType(TileType.GOAL).setNext(playfield.getTile(5, 4)).setPlayerID(1);
playfield.getTile(5, 4).setType(TileType.GOAL).setPlayerID(1);
playfield.getTile(5, 5).setType(TileType.NONE);
playfield.getTile(5, 6).setType(TileType.GOAL).setPlayerID(3);
playfield.getTile(5, 7).setType(TileType.GOAL).setNext(playfield.getTile(5, 6)).setPlayerID(3);
playfield.getTile(5, 8).setType(TileType.GOAL).setNext(playfield.getTile(5, 7)).setPlayerID(3);
playfield.getTile(5, 9).setType(TileType.GOAL).setNext(playfield.getTile(5, 8)).setPlayerID(3);
playfield.getTile(5, 10).setType(TileType.GOAL).setNext(playfield.getTile(5, 9)).setPlayerID(3);
playfield.getTile(5, 11).setType(TileType.GOAL).setNext(playfield.getTile(5, 10)).setPlayerID(3);
playfield.getTile(5, 12).setType(TileType.GOAL).setNext(playfield.getTile(5, 11)).setPlayerID(3);
playfield.getTile(5, 13).setType(TileType.GOAL).setNext(playfield.getTile(5, 12)).setPlayerID(3);
playfield.getTile(5, 14).setType(TileType.TOGOAL).setNext(playfield.getTile(6, 14)).setGoal(playfield.getTile(5, 13));
playfield.getTile(6, 0).setType(TileType.WAY).setNext(playfield.getTile(5, 0));
playfield.getTile(6, 1).setType(TileType.WAY).setNext(playfield.getTile(6, 0));
playfield.getTile(6, 2).setType(TileType.WAY).setNext(playfield.getTile(6, 1));
playfield.getTile(6, 3).setType(TileType.WAY).setNext(playfield.getTile(6, 2));
playfield.getTile(6, 4).setType(TileType.WAY).setNext(playfield.getTile(6, 3));
playfield.getTile(6, 5).setType(TileType.NONE);
playfield.getTile(6, 6).setType(TileType.WAY).setNext(playfield.getTile(7, 6));
playfield.getTile(6, 7).setType(TileType.WAY).setNext(playfield.getTile(6, 6));
playfield.getTile(6, 8).setType(TileType.WAY).setNext(playfield.getTile(6, 7));
playfield.getTile(6, 9).setType(TileType.NONE);
playfield.getTile(6, 10).setType(TileType.WAY).setNext(playfield.getTile(7, 10));
playfield.getTile(6, 11).setType(TileType.WAY).setNext(playfield.getTile(6, 10));
playfield.getTile(6, 12).setType(TileType.WAY).setNext(playfield.getTile(6, 11));
playfield.getTile(6, 13).setType(TileType.WAY).setNext(playfield.getTile(6, 12));
playfield.getTile(6, 14).setType(TileType.START).setNext(playfield.getTile(6, 13)).setPlayerID(3);
playfield.getTile(7, 0).setType(TileType.NONE);
playfield.getTile(7, 1).setType(TileType.NONE);
playfield.getTile(7, 2).setType(TileType.NONE);
playfield.getTile(7, 3).setType(TileType.NONE);
playfield.getTile(7, 4).setType(TileType.WAY).setNext(playfield.getTile(6, 4));
playfield.getTile(7, 5).setType(TileType.GOAL).setPlayerID(4);
playfield.getTile(7, 6).setType(TileType.WAY).setNext(playfield.getTile(8, 6));
playfield.getTile(7, 7).setType(TileType.NONE);
playfield.getTile(7, 8).setType(TileType.WAY).setNext(playfield.getTile(6, 8));
playfield.getTile(7, 9).setType(TileType.NONE);
playfield.getTile(7, 10).setType(TileType.WAY).setNext(playfield.getTile(8, 10));
playfield.getTile(7, 11).setType(TileType.NONE);
playfield.getTile(7, 12).setType(TileType.NONE);
playfield.getTile(7, 13).setType(TileType.NONE);
playfield.getTile(7, 14).setType(TileType.NONE);
playfield.getTile(8, 0).setType(TileType.NONE);
playfield.getTile(8, 1).setType(TileType.NONE);
playfield.getTile(8, 2).setType(TileType.NONE);
playfield.getTile(8, 3).setType(TileType.NONE);
playfield.getTile(8, 4).setType(TileType.WAY).setNext(playfield.getTile(7, 4));
playfield.getTile(8, 5).setType(TileType.GOAL).setNext(playfield.getTile(7, 5)).setPlayerID(4);
playfield.getTile(8, 6).setType(TileType.WAY).setNext(playfield.getTile(9, 6));
playfield.getTile(8, 7).setType(TileType.NONE);
playfield.getTile(8, 8).setType(TileType.WAY).setNext(playfield.getTile(7, 8));
playfield.getTile(8, 9).setType(TileType.NONE);
playfield.getTile(8, 10).setType(TileType.WAY).setNext(playfield.getTile(9, 10));
playfield.getTile(8, 11).setType(TileType.NONE);
playfield.getTile(8, 12).setType(TileType.NONE);
playfield.getTile(8, 13).setType(TileType.HOME).setPlayerID(3);
playfield.getTile(8, 14).setType(TileType.HOME).setPlayerID(3);
playfield.getTile(9, 0).setType(TileType.NONE);
playfield.getTile(9, 1).setType(TileType.NONE);
playfield.getTile(9, 2).setType(TileType.NONE);
playfield.getTile(9, 3).setType(TileType.NONE);
playfield.getTile(9, 4).setType(TileType.WAY).setNext(playfield.getTile(8, 4));
playfield.getTile(9, 5).setType(TileType.GOAL).setNext(playfield.getTile(8, 5)).setPlayerID(4);
playfield.getTile(9, 6).setType(TileType.WAY).setNext(playfield.getTile(10, 6));
playfield.getTile(9, 7).setType(TileType.NONE);
playfield.getTile(9, 8).setType(TileType.WAY).setNext(playfield.getTile(8, 8));
playfield.getTile(9, 9).setType(TileType.WAY).setNext(playfield.getTile(9, 8));
playfield.getTile(9, 10).setType(TileType.WAY).setNext(playfield.getTile(9, 9));
playfield.getTile(9, 11).setType(TileType.NONE);
playfield.getTile(9, 12).setType(TileType.NONE);
playfield.getTile(9, 13).setType(TileType.HOME).setPlayerID(3);
playfield.getTile(9, 14).setType(TileType.HOME).setPlayerID(3);
playfield.getTile(10, 0).setType(TileType.HOME).setPlayerID(4);
playfield.getTile(10, 1).setType(TileType.HOME).setPlayerID(4);
playfield.getTile(10, 2).setType(TileType.NONE);
playfield.getTile(10, 3).setType(TileType.NONE);
playfield.getTile(10, 4).setType(TileType.WAY).setNext(playfield.getTile(9, 4));
playfield.getTile(10, 5).setType(TileType.GOAL).setNext(playfield.getTile(9, 5)).setPlayerID(4);
playfield.getTile(10, 6).setType(TileType.WAY).setNext(playfield.getTile(11, 6));
playfield.getTile(10, 7).setType(TileType.NONE);
playfield.getTile(10, 8).setType(TileType.NONE);
playfield.getTile(10, 9).setType(TileType.NONE);
playfield.getTile(10, 10).setType(TileType.NONE);
playfield.getTile(10, 11).setType(TileType.NONE);
playfield.getTile(10, 12).setType(TileType.NONE);
playfield.getTile(10, 13).setType(TileType.HOME).setPlayerID(3);
playfield.getTile(10, 14).setType(TileType.HOME).setPlayerID(3);
playfield.getTile(11, 0).setType(TileType.HOME).setPlayerID(4);
playfield.getTile(11, 1).setType(TileType.HOME).setPlayerID(4);
playfield.getTile(11, 2).setType(TileType.NONE);
playfield.getTile(11, 3).setType(TileType.NONE);
playfield.getTile(11, 4).setType(TileType.START).setNext(playfield.getTile(10, 4)).setPlayerID(4);
playfield.getTile(11, 5).setType(TileType.TOGOAL).setNext(playfield.getTile(11, 4)).setGoal(playfield.getTile(10, 5));
playfield.getTile(11, 6).setType(TileType.WAY).setNext(playfield.getTile(11, 5));
playfield.getTile(11, 7).setType(TileType.NONE);
playfield.getTile(11, 8).setType(TileType.NONE);
playfield.getTile(11, 9).setType(TileType.NONE);
playfield.getTile(11, 10).setType(TileType.NONE);
playfield.getTile(11, 11).setType(TileType.NONE);
playfield.getTile(11, 12).setType(TileType.NONE);
playfield.getTile(11, 13).setType(TileType.HOME).setPlayerID(3);
playfield.getTile(11, 14).setType(TileType.HOME).setPlayerID(3);
		
	}
}
