package com.company.model;

import com.company.model.Playfield;
import com.company.model.TileType;
import com.company.model.Tile;
public class GEN_PlayfieldCreator {
	public static void createPlayfield(Playfield playfield) {
int sizex = 11;int sizey = 11;playfield.setupTiles(sizex, sizey);playfield.setTile(0, 0, new Tile());playfield.getTile(0, 0).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(2);
playfield.setTile(0, 1, new Tile());playfield.getTile(0, 1).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(2);
playfield.setTile(0, 2, new Tile());playfield.getTile(0, 2).setType(TileType.NONE);
playfield.setTile(0, 3, new Tile());playfield.getTile(0, 3).setType(TileType.NONE);
playfield.setTile(0, 4, new Tile());playfield.getTile(0, 4).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(0, 5, new Tile());playfield.getTile(0, 5).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(0, 6, new Tile());playfield.getTile(0, 6).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(3);
playfield.setTile(0, 7, new Tile());playfield.getTile(0, 7).setType(TileType.NONE);
playfield.setTile(0, 8, new Tile());playfield.getTile(0, 8).setType(TileType.NONE);
playfield.setTile(0, 9, new Tile());playfield.getTile(0, 9).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(3);
playfield.setTile(0, 10, new Tile());playfield.getTile(0, 10).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(3);
playfield.setTile(1, 0, new Tile());playfield.getTile(1, 0).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(2);
playfield.setTile(1, 1, new Tile());playfield.getTile(1, 1).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(2);
playfield.setTile(1, 2, new Tile());playfield.getTile(1, 2).setType(TileType.NONE);
playfield.setTile(1, 3, new Tile());playfield.getTile(1, 3).setType(TileType.NONE);
playfield.setTile(1, 4, new Tile());playfield.getTile(1, 4).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(1, 5, new Tile());playfield.getTile(1, 5).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(3);
playfield.setTile(1, 6, new Tile());playfield.getTile(1, 6).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(1, 7, new Tile());playfield.getTile(1, 7).setType(TileType.NONE);
playfield.setTile(1, 8, new Tile());playfield.getTile(1, 8).setType(TileType.NONE);
playfield.setTile(1, 9, new Tile());playfield.getTile(1, 9).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(3);
playfield.setTile(1, 10, new Tile());playfield.getTile(1, 10).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(3);
playfield.setTile(2, 0, new Tile());playfield.getTile(2, 0).setType(TileType.NONE);
playfield.setTile(2, 1, new Tile());playfield.getTile(2, 1).setType(TileType.NONE);
playfield.setTile(2, 2, new Tile());playfield.getTile(2, 2).setType(TileType.NONE);
playfield.setTile(2, 3, new Tile());playfield.getTile(2, 3).setType(TileType.NONE);
playfield.setTile(2, 4, new Tile());playfield.getTile(2, 4).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(2, 5, new Tile());playfield.getTile(2, 5).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(3);
playfield.setTile(2, 6, new Tile());playfield.getTile(2, 6).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(2, 7, new Tile());playfield.getTile(2, 7).setType(TileType.NONE);
playfield.setTile(2, 8, new Tile());playfield.getTile(2, 8).setType(TileType.NONE);
playfield.setTile(2, 9, new Tile());playfield.getTile(2, 9).setType(TileType.NONE);
playfield.setTile(2, 10, new Tile());playfield.getTile(2, 10).setType(TileType.NONE);
playfield.setTile(3, 0, new Tile());playfield.getTile(3, 0).setType(TileType.NONE);
playfield.setTile(3, 1, new Tile());playfield.getTile(3, 1).setType(TileType.NONE);
playfield.setTile(3, 2, new Tile());playfield.getTile(3, 2).setType(TileType.NONE);
playfield.setTile(3, 3, new Tile());playfield.getTile(3, 3).setType(TileType.NONE);
playfield.setTile(3, 4, new Tile());playfield.getTile(3, 4).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(3, 5, new Tile());playfield.getTile(3, 5).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(3);
playfield.setTile(3, 6, new Tile());playfield.getTile(3, 6).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(3, 7, new Tile());playfield.getTile(3, 7).setType(TileType.NONE);
playfield.setTile(3, 8, new Tile());playfield.getTile(3, 8).setType(TileType.NONE);
playfield.setTile(3, 9, new Tile());playfield.getTile(3, 9).setType(TileType.NONE);
playfield.setTile(3, 10, new Tile());playfield.getTile(3, 10).setType(TileType.NONE);
playfield.setTile(4, 0, new Tile());playfield.getTile(4, 0).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(2);
playfield.setTile(4, 1, new Tile());playfield.getTile(4, 1).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(4, 2, new Tile());playfield.getTile(4, 2).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(4, 3, new Tile());playfield.getTile(4, 3).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(4, 4, new Tile());playfield.getTile(4, 4).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(4, 5, new Tile());playfield.getTile(4, 5).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(3);
playfield.setTile(4, 6, new Tile());playfield.getTile(4, 6).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(4, 7, new Tile());playfield.getTile(4, 7).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(4, 8, new Tile());playfield.getTile(4, 8).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(4, 9, new Tile());playfield.getTile(4, 9).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(4, 10, new Tile());playfield.getTile(4, 10).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(5, 0, new Tile());playfield.getTile(5, 0).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(5, 1, new Tile());playfield.getTile(5, 1).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(2);
playfield.setTile(5, 2, new Tile());playfield.getTile(5, 2).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(2);
playfield.setTile(5, 3, new Tile());playfield.getTile(5, 3).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(2);
playfield.setTile(5, 4, new Tile());playfield.getTile(5, 4).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(2);
playfield.setTile(5, 5, new Tile());playfield.getTile(5, 5).setType(TileType.NONE);
playfield.setTile(5, 6, new Tile());playfield.getTile(5, 6).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(4);
playfield.setTile(5, 7, new Tile());playfield.getTile(5, 7).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(4);
playfield.setTile(5, 8, new Tile());playfield.getTile(5, 8).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(4);
playfield.setTile(5, 9, new Tile());playfield.getTile(5, 9).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(4);
playfield.setTile(5, 10, new Tile());playfield.getTile(5, 10).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(6, 0, new Tile());playfield.getTile(6, 0).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(6, 1, new Tile());playfield.getTile(6, 1).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(6, 2, new Tile());playfield.getTile(6, 2).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(6, 3, new Tile());playfield.getTile(6, 3).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(6, 4, new Tile());playfield.getTile(6, 4).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(6, 5, new Tile());playfield.getTile(6, 5).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(5);
playfield.setTile(6, 6, new Tile());playfield.getTile(6, 6).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(6, 7, new Tile());playfield.getTile(6, 7).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(6, 8, new Tile());playfield.getTile(6, 8).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(6, 9, new Tile());playfield.getTile(6, 9).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(6, 10, new Tile());playfield.getTile(6, 10).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(4);
playfield.setTile(7, 0, new Tile());playfield.getTile(7, 0).setType(TileType.NONE);
playfield.setTile(7, 1, new Tile());playfield.getTile(7, 1).setType(TileType.NONE);
playfield.setTile(7, 2, new Tile());playfield.getTile(7, 2).setType(TileType.NONE);
playfield.setTile(7, 3, new Tile());playfield.getTile(7, 3).setType(TileType.NONE);
playfield.setTile(7, 4, new Tile());playfield.getTile(7, 4).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(7, 5, new Tile());playfield.getTile(7, 5).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(5);
playfield.setTile(7, 6, new Tile());playfield.getTile(7, 6).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(7, 7, new Tile());playfield.getTile(7, 7).setType(TileType.NONE);
playfield.setTile(7, 8, new Tile());playfield.getTile(7, 8).setType(TileType.NONE);
playfield.setTile(7, 9, new Tile());playfield.getTile(7, 9).setType(TileType.NONE);
playfield.setTile(7, 10, new Tile());playfield.getTile(7, 10).setType(TileType.NONE);
playfield.setTile(8, 0, new Tile());playfield.getTile(8, 0).setType(TileType.NONE);
playfield.setTile(8, 1, new Tile());playfield.getTile(8, 1).setType(TileType.NONE);
playfield.setTile(8, 2, new Tile());playfield.getTile(8, 2).setType(TileType.NONE);
playfield.setTile(8, 3, new Tile());playfield.getTile(8, 3).setType(TileType.NONE);
playfield.setTile(8, 4, new Tile());playfield.getTile(8, 4).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(8, 5, new Tile());playfield.getTile(8, 5).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(5);
playfield.setTile(8, 6, new Tile());playfield.getTile(8, 6).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(8, 7, new Tile());playfield.getTile(8, 7).setType(TileType.NONE);
playfield.setTile(8, 8, new Tile());playfield.getTile(8, 8).setType(TileType.NONE);
playfield.setTile(8, 9, new Tile());playfield.getTile(8, 9).setType(TileType.NONE);
playfield.setTile(8, 10, new Tile());playfield.getTile(8, 10).setType(TileType.NONE);
playfield.setTile(9, 0, new Tile());playfield.getTile(9, 0).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(5);
playfield.setTile(9, 1, new Tile());playfield.getTile(9, 1).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(5);
playfield.setTile(9, 2, new Tile());playfield.getTile(9, 2).setType(TileType.NONE);
playfield.setTile(9, 3, new Tile());playfield.getTile(9, 3).setType(TileType.NONE);
playfield.setTile(9, 4, new Tile());playfield.getTile(9, 4).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(9, 5, new Tile());playfield.getTile(9, 5).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(5);
playfield.setTile(9, 6, new Tile());playfield.getTile(9, 6).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(9, 7, new Tile());playfield.getTile(9, 7).setType(TileType.NONE);
playfield.setTile(9, 8, new Tile());playfield.getTile(9, 8).setType(TileType.NONE);
playfield.setTile(9, 9, new Tile());playfield.getTile(9, 9).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(4);
playfield.setTile(9, 10, new Tile());playfield.getTile(9, 10).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(4);
playfield.setTile(10, 0, new Tile());playfield.getTile(10, 0).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(5);
playfield.setTile(10, 1, new Tile());playfield.getTile(10, 1).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(5);
playfield.setTile(10, 2, new Tile());playfield.getTile(10, 2).setType(TileType.NONE);
playfield.setTile(10, 3, new Tile());playfield.getTile(10, 3).setType(TileType.NONE);
playfield.setTile(10, 4, new Tile());playfield.getTile(10, 4).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(5);
playfield.setTile(10, 5, new Tile());playfield.getTile(10, 5).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(10, 6, new Tile());playfield.getTile(10, 6).setType(TileType.WAY).setNext(playfield.getTile(0, 2));
playfield.setTile(10, 7, new Tile());playfield.getTile(10, 7).setType(TileType.NONE);
playfield.setTile(10, 8, new Tile());playfield.getTile(10, 8).setType(TileType.NONE);
playfield.setTile(10, 9, new Tile());playfield.getTile(10, 9).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(4);
playfield.setTile(10, 10, new Tile());playfield.getTile(10, 10).setType(TileType.HOME).setNext(playfield.getTile(0, 2)).setPlayerID(4);
		
	}
}
